In [1]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /Users/krushi/opt/anaconda3/lib/python3.9/site-packages (1.0.2)
Requirement already satisfied: numpy>=1.14.6 in /Users/krushi/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn) (1.22.4)
Requirement already satisfied: scipy>=1.1.0 in /Users/krushi/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn) (1.7.3)
Requirement already satisfied: joblib>=0.11 in /Users/krushi/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/krushi/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn) (2.2.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from sklearn.model_selection import KFold, cross_val_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

In [3]:
# Load the data from the CSV file
data = pd.read_csv("Bumrah_.csv")

In [4]:
data.Opposition.unique()

array(['Australia', 'Zimbabwe', 'New Zealand', 'England', 'Pakistan',
       'Sri Lanka', 'South Africa', 'Bangladesh', 'West', 'Afghanistan',
       'Netherlands'], dtype=object)

In [5]:
data

    Overs  Runs  Wickets  Economy  Innings    Opposition        Ground
0      10    40        2     4.00        1     Australia        Sydney
1      10    28        4     2.84        1      Zimbabwe        Harare
2       6    27        1     4.50        1      Zimbabwe        Harare
3      10    22        4     2.20        1      Zimbabwe        Harare
4       8    29        0     3.62        1   New Zealand    Dharamsala
..    ...   ...      ...      ...      ...           ...           ...
81     10    45        1     4.50        1   New Zealand    Dharamsala
82      7    32        3     4.68        2       England       Lucknow
83      5     8        1     1.60        2     Sri Lanka      Wankhede
84      5    14        0     2.80        2  South Africa  Eden Gardens
85      9    33        2     3.66        2   Netherlands     Bengaluru

[86 rows x 7 columns]

In [8]:
# Separate features (X) from the target variable (y)
X = data.drop('Wickets', axis=1)
y = data['Wickets']

labelencoder_1 = LabelEncoder()
X['Opposition'] = labelencoder_1.fit_transform(X['Opposition'])

labelencoder_2 = LabelEncoder()
X['Ground'] = labelencoder_2.fit_transform(X['Ground'])

labelencoder_3 = LabelEncoder()
X['Innings'] = labelencoder_3.fit_transform(X['Innings'])

labelencoder_4 = LabelEncoder()
X['Overs'] = labelencoder_4.fit_transform(X['Overs'])

#labelencoder_5 = LabelEncoder()
#X['Economy'] = labelencoder_5.fit_transform(X['Economy'])

X = X[['Opposition','Ground','Innings','Overs']]

# K-fold cross-validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)
mse_scores = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Train the model on the training data
    model = RandomForestRegressor(random_state=42)
    model.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = model.predict(X_test)

    # Calculate the mean squared error
    mse = mean_squared_error(y_test, y_pred)
    mse_scores.append(mse)

# Calculate the average mean squared error
avg_mse = sum(mse_scores) / len(mse_scores)
print("Average Mean Squared Error:", avg_mse)

Opposition = input("Enter the Opposition : ")
Ground = input("Enter the Ground : ")
Innings = input("Enter the Innings : ")
Overs = input("Enter the Avg_Overs : ")
#Economy = input("Enter Avg_Economy : ")

new_data = {
    'Opposition': Opposition,
    'Ground': Ground,
 #   'Economy': float(Economy),
    'Innings': int(Innings),
    'Overs': int(Overs)
}


index = [0]  # Index can be a list of integers
new_data = pd.DataFrame(new_data, index=index)


new_data['Opposition'] = labelencoder_1.transform(new_data['Opposition'])
new_data['Ground'] = labelencoder_2.transform(new_data['Ground'])
new_data['Innings'] = labelencoder_3.transform(new_data['Innings'])
new_data['Overs'] = labelencoder_4.transform(new_data['Overs'])
#new_data['Economy'] = labelencoder_5.transform(new_data['Economy'])


#labelencoder_1 = LabelEncoder()
#new_data['Opposition'] = labelencoder_1.fit_transform(new_data['Opposition'])

# Label encode the 'Ground' feature
#labelencoder_2 = LabelEncoder()
#new_data['Ground'] = labelencoder_2.fit_transform(new_data['Ground'])

#labelencoder_3 = LabelEncoder()
#new_data['Innings'] = labelencoder_3.fit_transform(new_data['Innings'])

#labelencoder_4 = LabelEncoder()
#new_data['Overs'] = labelencoder_4.fit_transform(new_data['Overs'])

#labelencoder_5 = LabelEncoder()
#new_data['Economy'] = labelencoder_5.fit_transform(new_data['Economy'])


print(new_data)

predicted_Wickets = model.predict(new_data)
print(f"Predicted Wickets for the future game against {Opposition} in {Ground}:", predicted_Wickets)

Average Mean Squared Error: 1.7252422150220847
Enter the Opposition : New Zealand
Enter the Ground : Wankhede
Enter the Innings : 2
Enter the Avg_Overs : 10
   Opposition  Ground  Innings  Overs
0           5      41        1      6
Predicted Wickets for the future game against New Zealand in Wankhede: [1.05333333]