In [1]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /Users/krushi/opt/anaconda3/lib/python3.9/site-packages (1.0.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/krushi/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: scipy>=1.1.0 in /Users/krushi/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn) (1.7.3)
Requirement already satisfied: joblib>=0.11 in /Users/krushi/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn) (1.1.0)
Requirement already satisfied: numpy>=1.14.6 in /Users/krushi/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn) (1.22.4)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [1]:
import pandas as pd
from sklearn.model_selection import KFold, cross_val_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler


# Load the data from the CSV file
data = pd.read_csv("Shubman_Gill.csv")

In [2]:
data

,Runs,Minutes,Balls_faced,4s,6s,Strike_Rate,Position,Dismissal,Innings,Opposition,Ground
0,9,32,21,1,0,42.85,3,caught,1,New Zealand,Hamilton
1,7,13,11,1,0,63.63,3,caught,1,New Zealand,Wellington
2,33,37,39,3,1,84.61,2,lbw,1,Australia,Canberra
3,64,83,53,6,2,120.75,2,run out,1,West,Port of Spain
4,43,70,49,5,0,87.75,2,caught,2,West,Port of Spain
5,98,162,98,7,2,100.00,2,not out,1,West,Port of Spain
6,82,130,72,10,1,113.88,2,not out,2,Zimbabwe,Harare
7,33,62,34,6,0,97.05,3,caught,2,Zimbabwe,Harare
8,130,145,97,15,1,134.02,3,caught,1,Zimbabwe,Harare
9,3,13,7,0,0,42.85,2,bowled,2,South Africa,Lucknow
10,28,34,26,5,0,107.69,2,caught,2,South Africa,Ranchi
11,49,82,57,8,0,85.96,2,lbw,2,South Africa,Delhi
12,50,93,65,1,3,76.92,2,caught,1,New Zealand,Auckland
13,45,49,42,4,1,107.14,2,not out,1,New Zealand,Hamilton
14,13,34,22,2,0,59.09,2,caught,1,New Zealand,Christchurch
15,70,89,60,11,0,116.66,2,lbw,1,Sri Lanka,Guwahati
16,21,25,12,5,0,175.00,2,caught,2,Sri Lanka,Eden Gardens
17,116,147,97,14,2,119.58,2,bowled,1,Sri Lanka,Thiruvananthapuram
18,208,225,149,19,9,139.59,2,caught,1,New Zealand,Hyderabad
19,40,88,53,6,0,75.47,2,not out,2,New Zealand,Raipur
20,112,120,78,13,5,143.58,2,caught,1,New Zealand,Indore
21,20,57,31,3,0,64.51,2,caught,2,Australia,Wankhede
22,0,4,2,0,0,0.00,2,caught,1,Australia,Visakhapatnam
23,37,62,49,4,1,75.51,2,lbw,2,Australia,Chennai
24,7,19,16,1,0,43.75,2,caught,2,West,Bridgetown
25,34,72,49,5,0,69.38,2,caught,1,West,Bridgetown
26,85,168,92,11,0,92.39,2,caught,1,West,Tarouba
27,10,75,32,1,0,31.25,2,bowled,1,Pakistan,Pallekele
28,67,87,62,8,1,108.06,2,not out,2,Nepal,Pallekele
29,58,83,52,10,0,111.53,2,caught,1,Pakistan,Colombo (RPS)
30,19,54,25,2,0,76.00,2,bowled,1,Sri Lanka,Colombo (RPS)
31,121,185,133,8,5,90.97,2,caught,2,Bangladesh,Colombo (RPS)
32,27,26,19,6,0,142.10,2,not out,2,Sri Lanka,Colombo (RPS)
33,74,110,63,6,2,117.46,2,bowled,2,Australia,Mohali
34,104,155,97,6,4,107.21,2,caught,1,Australia,Indore
35,16,11,11,4,0,145.45,2,caught,2,Pakistan,Ahmedabad
36,53,80,55,5,2,96.36,2,caught,2,Bangladesh,Pune
37,26,53,31,5,0,83.87,2,caught,2,New Zealand,Dharamsala
38,9,18,13,1,0,69.23,2,bowled,1,England,Lucknow
39,92,136,92,11,2,100.00,2,caught,1,Sri Lanka,Wankhede
40,23,54,24,4,1,95.83,2,bowled,1,South Africa,Eden Gardens
41,35,42,20,2,3,175.00,2,not out,1,Netherlands,Bengaluru

In [3]:
data.Opposition.unique()

array(['New Zealand', 'Australia', 'West', 'Zimbabwe', 'South Africa',
       'Sri Lanka', 'Pakistan', 'Nepal', 'Bangladesh', 'England',
       'Netherlands'], dtype=object)

In [4]:
# Separate features (X) from the target variable (y)
X = data.drop('Runs', axis=1)
y = data['Runs']

labelencoder = LabelEncoder()
X['Dismissal'] = labelencoder.fit_transform(X['Dismissal'])

labelencoder_1 = LabelEncoder()
X['Opposition'] = labelencoder_1.fit_transform(X['Opposition'])

labelencoder_2 = LabelEncoder()
X['Ground'] = labelencoder_2.fit_transform(X['Ground'])

labelencoder_2 = LabelEncoder()
X['Innings'] = labelencoder_2.fit_transform(X['Innings'])

In [5]:
X = X[['Dismissal','Opposition','Ground','Innings']]

In [6]:

#labelencoder_3 = LabelEncoder()
#X['Start Date'] = labelencoder_3.fit_transform(X['Start Date'])

# K-fold cross-validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)
mse_scores = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Train the model on the training data
    model = RandomForestRegressor(random_state=42)
    model.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = model.predict(X_test)

    # Calculate the mean squared error
    mse = mean_squared_error(y_test, y_pred)
    mse_scores.append(mse)

# Calculate the average mean squared error
avg_mse = sum(mse_scores) / len(mse_scores)
print("Average Mean Squared Error:", avg_mse)


Opposition = input("Enter the Opposition : ")
Ground = input("Enter the Ground : ")
Position = input("Enter Position : ")
Innings = input("Enter the Innings : ")


# New data for the future game
new_data = {
    'Opposition': Opposition,
    'Ground': Ground,
    #'Start Date': '11/15/2023',
    'Position': int(Position),
    'Innings': int(Innings)
}

# Preprocess the new data
index = [0]  # Index can be a list of integers
new_data = pd.DataFrame(new_data, index=index)

print(new_data)

# Label encode the 'Opposition' feature
labelencoder_1 = LabelEncoder()
new_data['Opposition'] = labelencoder_1.fit_transform(new_data['Opposition'])

# Label encode the 'Ground' feature
labelencoder_2 = LabelEncoder()
new_data['Ground'] = labelencoder_2.fit_transform(new_data['Ground'])

#labelencoder_3 = LabelEncoder()
#X['Start Date'] = labelencoder_3.fit_transform(X['Start Date'])


# divide date into seperate columns
# 
# Scale the 'Date' feature
#scaler = MinMaxScaler()
#scaler.fit(X_train['Start Date'].values.reshape(-1, 1))
#new_data['Start Date'] = scaler.transform(new_data['Start Date'].values.reshape(-1, 1))

# Make a prediction
predicted_runs = model.predict(new_data)
print(f"Predicted runs for the future game against {Opposition} in {Ground}:", predicted_runs)

Average Mean Squared Error: 2090.807479
Enter the Opposition : New Zealand
Enter the Ground : Wankhede
Enter Position : 2
Enter the Innings : 1
    Opposition    Ground  Position  Innings
0  New Zealand  Wankhede         2        1
Predicted runs for the future game against New Zealand in Wankhede: [54.05]

/Users/krushi/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Position
Feature names seen at fit time, yet now missing:
- Dismissal

  warnings.warn(message, FutureWarning)